name: Release

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and publish with Gradle
        run: ./gradlew build curseforge --stacktrace
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
